# Base configs
baseurl: "https://aztejeda.me"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-140402967-1"

# UI configs
title: "Adam Tejeda"
subtitle: ""
author: "Adam Tejeda"
header:
 title: "Photos and More"
 subtitle: " - Adam Tejeda"
footer:
 name: "Hey there, my name is Adam"
 bio: "Hi! Hopefully you're here to check out my photos and see that I am a worthwhile canidate for the position of SA Historian. I've been interested in taking pictures ever
 since I was a little kid, using my parents' camera whenever I could. Since getting my first camera, the Nikon D3300 I've been taking photos as much as possible. I was 
 able to get an upgrade, going to the Nikon D5600 which was a huge upgrade from my first camera. I've had a lot of practice with this camera, and the photos on this page are all from my camera. I hope you enjoy them and can vote for me for the 2019-2020 School year :)"

web_design: "AJ"
social_urls:
  twitter: "https://www.twitter.com/aztejeda"
  instagram: "https://www.instagram.com/aztejeda"
