# Base configs
baseurl: "aztejeda.me"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-140402967-1"

# UI configs
title: "Adam Tejeda"
subtitle: ""
author: "Adam Tejeda"
header:
 title: "Photos and More"
 subtitle: " - Adam Tejeda"
footer:
 name: "Hey there, my name is Adam"
 bio: "Work in Progress"

web_design: "AJ"
social_urls:
  twitter: "https://www.twitter.com/aztejeda"
  instagram: "https://www.instagram.com/aztejeda"
